
mp.openapi.extensions.smallrye.info.title=Automotive JavaEE API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Automotive management API built with Jakarta EE
